chore: dotfiles update!

diff --git a/.config/wlogout/actions b/.config/wlogout/actions
--- a/.config/wlogout/actions
+++ b/.config/wlogout/actions
@@ -1,12 +1,17 @@
 #!/usr/bin/env bash
 
-# Ask for confirmation
-cdialog () {
-    yad --title='Confirm?' --css="box { padding: 0.5rem; }" --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="You sure you wanna $1?" --text-align=center --align=center --justify=center --buttons-layout=spread
+# Ask for confirmation using zenity
+cdialog() {
+    zenity --question --title="Confirm" --text="Are you sure you want to $1?" --width=200
+    return $?
 }
 
-notify () {
-    notify-send --expire-time=1200 --icon="system-shutdown-symbolic" "System Info" "$1"
+# Notify function with optional sleep time parameter
+notify() {
+    local message=$1
+    local delay=${2:-2} # Default to 2 seconds if not provided
+    notify-send --expire-time=1200 --icon="system-shutdown-symbolic" "System Info" "$message"
+    sleep $delay # Using the provided sleep time or default
 }
 
 cdialog "$1"
@@ -14,30 +19,37 @@ cdialog "$1"
 if [[ "$?" == 0 ]]; then
     playerctl --all-players stop
     sleep 0.25s
-    if [[ "$1" == 'shutdown' ]]; then
-        notify "Shutting down..."
-        sleep 0.25s
+    case "$1" in
+    'shutdown')
+        notify "Shutting down in 2 seconds..." 2
         systemctl poweroff
-    elif [[ "$1" == 'reboot' ]]; then
-        notify "Rebooting..."
-        sleep 0.25s
+        ;;
+    'reboot')
+        notify "Rebooting in 2 seconds..." 2
         systemctl reboot
-    elif [[ "$1" == 'hibernate' ]]; then
+        ;;
+    'hibernate')
         notify-send --expire-time=4000 --icon="system-shutdown-symbolic" "System Info" "Error! System doesn't support hibernation"
-    elif [[ "$1" == 'lock' ]]; then
-        notify "Locking..."
-        sleep 0.25s
+        ;;
+    'lock')
+        notify "Locking..." 0.5
         swaylock
-    elif [[ "$1" == 'suspend' ]]; then
-        notify "Suspending..."
+        ;;
+    'suspend')
+        notify "Suspending..." 0.5
         swaylock
         sleep 0.5s
         systemctl suspend
-    elif [[ "$1" == 'logout' ]]; then
-        notify "Logging out of Hyprland..."
-        sleep 0.25s
-        hyprctl dispatch exit none;
-    fi
+        ;;
+    'logout')
+        notify "Logging out of Hyprland..." 0.5
+        hyprctl dispatch exit none
+        ;;
+    *)
+        notify-send --expire-time=4000 --icon="arch-error-symbolic" "Error" "Uknown system command"
+        exit 1
+        ;;
+    esac
 else
     exit
 fi
